name: JBoss Fuse 6.2 image
maintainers:
- Jon Walton <jwalton@redhat.com>
description: |
  This image provides a base installation of JBoss Fuse 6.2.1 and JBoss
  Developer Studio with the Integration Stack plugins installed.  A root Fabric
  has also been created with the LoanBroker example deployed to four child
  containers.
layer:
  cpus: 2
  mem: 4096
