name: OpenShift 3.0.1 offline image with Jim's demo
maintainers:
- Jim Minter <jminter@redhat.com>
description: |
  This image provides an all-in-one instance of OpenShift 3.0.1, including the
  master and node components, examples, GUI and web browser.  All S2I builder
  images are also included, and source code and dependencies for all examples
  apps is pre-downloaded, so no nothing extra is needed and the image can be
  run disconnected from the internet.  This image also includes all the
  components necessary for Jim's OpenShift 3.0.1 demo.
