name: Atomic Enterprise Platform 3.1 base image
maintainers:
- Jim Minter <jminter@redhat.com>
description: |
  This image provides a base instance of Atomic Enterprise Platform 3.1.
layer:
  cpus: 2
  mem: 4096
