name: OpenShift 3.0.1 all-in-one image
maintainers:
- Jim Minter <jminter@redhat.com>
description: |
  This image provides an all-in-one instance of OpenShift 3.0.1, including the
  master and node components, examples, GUI and web browser.  All S2I builder
  images are also included, but Internet connectivity is required to run.

  This image includes builder images and is vanilla, so is handy for SAs and
  consultants to replicate issues / experiment with the product with moderate
  Internet connectivity.
