name: OpenShift 3.0.1 all-in-one image
maintainers:
- Jim Minter <jminter@redhat.com>
description: |
  This image provides an all-in-one instance of OpenShift 3.0.1, including the
  master and node components, examples, GUI and web browser.  Nothing extra is
  needed.

  Run the VM and open the GUI.  Log in as *demo* and set your password.  There
  are full further instructions on the desktop.
layer:
  cpus: 2
  mem: 4096
