name: OpenShift 3.0.1 base image
maintainers:
- Jim Minter <jminter@redhat.com>
description: |
  This image provides a base instance of OpenShift 3.0.1, including the
  master and node components, examples, GUI and web browser.  No S2I builder
  images are included so the distribution is small, but Internet connectivity
  is required to run.
layer:
  cpus: 2
  mem: 4096
